### ISSUE TITLE
No error handler?

### ISSUE THREAD

**Issue by Avnerus** [feathersjs/authentication-oauth1#34]
Hi!
How come there is no error handler registered as in OAuth 2?
This disables the use of 'failureRedirect'

**Comment by daffl** [comment]
That looks like a bug? Should be fixable by registering the same one as in https://github.com/feathersjs/authentication-oauth2/blob/master/lib/index.js#L78 right?

**Comment by Avnerus** [comment]
Right. I did it locally and it works (Though I had to do it for the older version because I'm not yet ready to migrate to the new Feathers architecture).

While we're at it, I have another more complicated question regarding the error handler (I can open another issue if needed).
I am using a custom JWT authentication with cookies for my users, but also allowing them to "connect" their twitter/facebook accounts via OAuth1/2.
If the users clicks to connect their facebook account for example, but then press "Cancel", it activates the error handler and `failureRedirect`. I just want them to go back to screen they came from.
However, because of [this](https://github.com/feathersjs/authentication/blob/master/lib/express/failure-redirect.js#L10) line, the error handler deletes their JWT cookie and they are no longer authenticated on my site!
Am I doing something wrong? I had to comment out this line for it to work.
Thanks!

**Comment by daffl** [comment]
Can you submit a PR for the change you already tested and another issue for the other question? Might require some additional change as well but let's discuss there.

**Comment by Avnerus** [comment]
Ok done!
Thanks.

**Comment by daffl** [comment]
Closed via #35
