### ISSUE TITLE
Create custom formatter for returning an html page that calls back to parent window

### ISSUE THREAD

**Issue by ekryski** [feathersjs/authentication-oauth1#6]
This is meant as a replacement for [authentication-popups](https://github.com/feathersjs/feathers-authentication-popups). It literally can be a pretty bare bones HTML page with some JS that calls back to the parent window the the JWT accessToken and/or sets it in localstorage.

It will also remove the need for https://github.com/feathersjs/feathers-authentication-popups-github and any other provider specific repos.

There is no need for a cookie as the token can be embedded right in the JS script tag in the HTML response page.

Related to https://github.com/feathersjs/feathers-authentication-popups/issues/5

cc/ @marshallswain

**Comment by daffl** [comment]
Could this page be part of the feathers-authentication-popups repo and we depend on that?

**Comment by ekryski** [comment]
Technically yes but I don't think we even need the popups repo. When @marshallswain and I discussed that there really needn't be any other piece to it in order to call out. Just add a param to the auth client to tell it to open in a new window as described in feathersjs/feathers-authentication-popups#5.
